# NUMPY VS LISTS

**Lists are slow!
Numpy are Fast!**

Numpy converts integers to computer binary which is faster for the machine to read.


Lists use other build-in int type which contains multiple things : Size, reference cournt ,object count, object type


In python you can have multiple data type in a list and therefore require type checking when the machine is reading it.


Numpy doesn't require type checking when iterating through lists

Lists are scattered around in memory while


Numpy arrays use contiguous memory

 **Benefits**
 Effectively using our cache
 SIMD VECTOR Processing easier

In [ ]:
import numpy as np

In [4]:
import numpy as np
a = np.array([1,2,3])
print(a)
a.size

[1 2 3]


3

In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#get dimestion
a.ndim

1

In [ ]:
#get shape
a.shape

(2, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
#get size (number of bytes in the integer)(number of memory adresses)
a.itemsize

8

In [ ]:
#Get total size
a.size * a.itemsize


24

In [ ]:
a.nbytes

24

In [ ]:
b.size

6

**Accessing/Changing specific elements,rows,columns**





In [ ]:
a = np.array([[1,2,4,5],[2,5,6,8,]])
print(a)

[[1 2 4 5]
 [2 5 6 8]]


In [ ]:
#get a specific column
a[:,2]

array([4, 6])

In [ ]:
#get a specific row
a[0,:]

array([0, 0, 0], dtype=int32)

In [ ]:
# getting a little more fancy
a[0, 1:6:2]

array([0], dtype=int32)

**Initiailizing different types of arrays**

In [ ]:
#all zero's matrix

np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
#all 1's matrix

np.ones((4,3), dtype ='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
#Any other number
np.full((2,2,3) , 88)

array([[[88, 88, 88],
        [88, 88, 88]],

       [[88, 88, 88],
        [88, 88, 88]]])

In [ ]:
#any other number(full like)
np.full(a.shape,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [ ]:
#random decimal numbers
np.random.rand(4,2)

array([[0.30855815, 0.55559732],
       [0.09087432, 0.97127145],
       [0.5883242 , 0.64900724],
       [0.05078563, 0.71343748]])

In [ ]:
#random integer valuse
np.random.randint(100, size=(3,3))

array([[65,  5, 99],
       [41, 31,  7],
       [ 2, 70, 75]])

In [ ]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr , 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
from re import A
#array initialization question from yt video
a = np.ones((5,5), dtype = 'int32')

z = np.zeros((3,3) ,dtype = 'int32')
z[1,1] = 9
a[1:4,1:4] = z
print(a)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#Be careful when copying arrays!!

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

# b is basically pointing to a and not copying so we need to use ".copy"

[100   2   3]
[100   2   3]


#Mathematics
numpy is used alot for mathematics because of the elementwise operations that can be performed on arrays

In [ ]:
a = np.array([1,2,3,4])


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])

In [ ]:
b **2

array([1, 0, 1, 0])

#Linear Algebra

In [ ]:
 a = np.full((2,3) ,9)
 print(a)
 b = np.ones((3,2), dtype ='int32')
 print(b)


[[9 9 9]
 [9 9 9]]
[[1 1]
 [1 1]
 [1 1]]


In [ ]:
# columns of the first matrix must be equal to the row'a of the second one
np.matmul(b,a)

array([[18, 18, 18],
       [18, 18, 18],
       [18, 18, 18]])

In [ ]:
#determinant
#trace
#invers
#singular vector decomposition
#eigenvaluse
#matrix Norm


#Stasitics

In [ ]:
stats = np.array([1,3,7,3,5])
stats

array([1, 3, 7, 3, 5])

In [ ]:
np.min(stats)

np.int64(1)

Reorganizing Arrays

In [ ]:
before = np.array([[1,3,5,6], [5,6,7,9]])

print(before)


[[1 3 5 6]
 [5 6 7 9]]


In [ ]:
after = before.reshape((2,2,2))
print(after)

[[[1 3]
  [5 6]]

 [[5 6]
  [7 9]]]


In [ ]:
#vertically stacking vectors
v1 = np.array([1,2,4,5])
v2 = np.array ([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 4, 5],
       [5, 6, 7, 8],
       [1, 2, 4, 5],
       [5, 6, 7, 8]])

In [ ]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 4, 5, 5, 6, 7, 8, 1, 2, 4, 5, 5, 6, 7, 8])

#Miscellaneous

Load Data from File

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving test.txt to test.txt


In [ ]:
filedata = np.genfromtxt('test.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[83 45 91 23 64 11 39 68 90 12 55 33 72  5 98 27 43 87 14 66  7 35 58 20
 76  3 94 62 19 80 41  6 96 28 24 50 17 71 13 77 99 36  9 84 31  2 46 25
 88 60]


In [ ]:
#### Boolean Masking and Advanced indexing

In [ ]:
filedata[filedata > 60]

array([83, 91, 64, 68, 90, 72, 98, 87, 66, 76, 94, 62, 80, 96, 71, 77, 99,
       84, 88], dtype=int32)

In [ ]:
(((filedata > 50) & (filedata < 75)))

array([False, False, False, False,  True, False, False,  True, False,
       False,  True, False,  True, False, False, False, False, False,
       False,  True, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True])

In [ ]:
A[[0,4,5],3:5]